name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1.0.7
      with:
        toolchain: nightly
        override: true
        
    - name: Run tests
      uses: actions-rs/cargo@v1.0.3
      with:
        command: test
        args: --all-features --no-fail-fast
      env:
        CARGO_INCREMENTAL: '0'
        RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off'
        
    - name: Collect code coverage
      id: coverage
      uses: actions-rs/grcov@v0.1
    
    - name: Upload code coverage
      uses: codecov/codecov-action@v2.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./lcov.info
